# Generated by Django 4.2.10 on 2024-02-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='jsonresp',
            field=models.TextField(default={}, max_length=200),
        ),
        migrations.AddField(
            model_name='planner',
            name='loc',
            field=models.CharField(default='abcd', max_length=120),
            preserve_default=False,
        ),
    ]
