# Generated by Django 4.2.10 on 2024-02-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_planner_jsonresp_planner_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='jsonresp',
            field=models.TextField(default='', max_length=200),
        ),
    ]
